require("hunter.plugins-setup")
require("hunter.core.options")
require("hunter.core.keymaps")
require("hunter.core.colorscheme")
require("hunter.plugins.comment")
require("hunter.plugins.nvim-tree")
require("hunter.plugins.lualine")
require("hunter.plugins.telescope")
require("hunter.plugins.nvim-cmp")
require("hunter.plugins.lsp.mason")
require("hunter.plugins.lsp.lspconfig")
require("hunter.plugins.lsp.lspsaga")
require("hunter.plugins.autopairs")
require("hunter.plugins.treesitter")
require("hunter.plugins.gitsigns")

